apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-cd
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: docker.io/dhairya442/docker_exe:master-426486b-1711523107 # {"$imagepolicy": "test-cd:myapp"}
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
        - name: DB_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: DB_CONNECTION
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: DB_DATABASE
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: DB_HOST
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: DB_USERNAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: DB_PORT
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret-app
              key: DB_PASSWORD
