apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: test-cd 
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi